import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no'
        />
        <meta property='og:title' content='Create Next App' />
        <meta
          property='og:description'
          content='Generated by create next app'
        />
        {/* <meta property="og:image" content="" /> */}
        {/* <meta property="og:url" content="/" /> */}
        <meta property='og:type' content='website' />
        <link rel='icon' href='/favicon.ico' sizes='any' />
      </head>
      <body className='max-w-[32rem] w-full min-h-screen mr-auto ml-auto'>
        {children}
      </body>
    </html>
  );
}
